version: '3.2'
services:
  chassis_framework:
    image: dawapack:0.1-chassis-framework
    container_name: chassis_framework
    build:
      dockerfile: Dockerfile
      context: ./var/docker
    stop_grace_period: 5s
    stdin_open: true
    tty: true
    environment:
      ORIGIN: "eu"
      REGION: "eu-bucharest-1"
    volumes:
      - type: bind
        source: .
        target: /var/package
  chassis_rabbitmq:
    image: rabbitmq:3.9.0-management-alpine
    container_name: chassis_rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
  chassis_redis:
    image: redis:6.2-alpine
    container_name: chassis_redis
    restart: on-failure
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
